### ISSUE TITLE
unable to install from pip.

### ISSUE THREAD

**Issue by lordofkillz** [Deci-AI/super-gradients#1650] opened 2023-11-20 22:03 UTC
### 🐛 Describe the bug

I was unable to install from pip on windows 11 due to onnxruntime and pycocotools. 
after downloading source and removing these 2 from requirements and  installing from requirements.txt i was to install all. then was able to pip install them normally. 

### Versions

..

**Comment by yonglee7015** [comment] 2023-12-24 13:25
python version should be 3.10, it will solve this issues.

**Comment by Louis-Dupont** [comment] 2023-12-25 21:54
It looks like a duplicate of https://github.com/Deci-AI/super-gradients/issues/896
I'm closing this issue, @lordofkillz if the issue was due to something else feel free to re-open the PR with extra information

**Closed by Louis-Dupont** 2023-12-25 21:54 UTC
Labels: :sheep: Duplicate, install issue
