### ISSUE TITLE
psutil error when I am import from super_gradients.training import dataloaders

### ISSUE THREAD

**Issue by aloizo03** [Deci-AI/super-gradients#1596] opened 2023-10-31 09:06 UTC
### 🐛 Describe the bug

When I am import dataloader from supergradient I am geeting this error:

Traceback (most recent call last):
  File "/lustreFS/data/deepcamera/aloizou/HARESS/YOLO-NAS/train.py", line 16, in <module>
    from super_gradients.training import dataloaders
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/__init__.py", line 4, in <module>
    from super_gradients.training import losses, utils, datasets_utils, DataAugmentation, Trainer, KDTrainer, QATTrainer
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/training/__init__.py", line 2, in <module>
    import super_gradients.training.utils.distributed_training_utils as distributed_training_utils
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/training/utils/__init__.py", line 13, in <module>
    from super_gradients.training.utils.early_stopping import EarlyStop
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/training/utils/early_stopping.py", line 1, in <module>
    from super_gradients.training.utils.callbacks import PhaseCallback, Phase, PhaseContext
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/training/utils/callbacks/__init__.py", line 2, in <module>
    from super_gradients.training.utils.callbacks.callbacks import (
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/training/utils/callbacks/callbacks.py", line 29, in <module>
    from super_gradients.common.sg_loggers.time_units import GlobalBatchStepNumber, EpochNumber
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/common/sg_loggers/__init__.py", line 1, in <module>
    from super_gradients.common.sg_loggers.base_sg_logger import BaseSGLogger
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/common/sg_loggers/base_sg_logger.py", line 20, in <module>
    from super_gradients.common.environment.monitoring import SystemMonitor
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/common/environment/monitoring/__init__.py", line 1, in <module>
    from super_gradients.common.environment.monitoring.monitoring import SystemMonitor
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/common/environment/monitoring/monitoring.py", line 5, in <module>
    from super_gradients.common.environment.monitoring import disk, virtual_memory, network, cpu, gpu
  File "/trinity/home/aloizou/data/aloizou/miniconda3/envs/yolo_nas_env_test/lib/python3.10/site-packages/super_gradients/common/environment/monitoring/disk.py", line 5, in <module>
    buffer_io_read_bytes = psutil.disk_io_counters().read_bytes
AttributeError: 'NoneType' object has no attribute 'read_bytes'

I tried also to remove it and install the latest version and I am still getting this error.
I am using a HPC for the training with TrinityX operating system

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.5 (Green Obsidian) (x86_64)
GCC version: (GCC) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-348.23.1.el8_5.x86_64-x86_64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           2
NUMA node(s):        8
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               1
Model name:          AMD EPYC 7313 16-Core Processor
Stepping:            1
CPU MHz:             3000.000
CPU max MHz:         3729.4919
CPU min MHz:         1500.0000
BogoMIPS:            6000.55
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-3,32-35
NUMA node1 CPU(s):   4-7,36-39
NUMA node2 CPU(s):   8-11,40-43
NUMA node3 CPU(s):   12-15,44-47
NUMA node4 CPU(s):   16-19,48-51
NUMA node5 CPU(s):   20-23,52-55
NUMA node6 CPU(s):   24-27,56-59
NUMA node7 CPU(s):   28-31,60-63
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] onnx==1.13.0
[pip3] onnx-simplifier==0.4.35
[pip3] onnxruntime==1.15.1
[pip3] torch==2.1.0
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] torchmetrics              0.8.0                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by BloodAxe** [comment] 2023-10-31 10:16
Can you please run `pip freeze` and post it here? Looks like some psutil versions are not broken.
Possible duplicate: https://github.com/Deci-AI/super-gradients/issues/1247

**Comment by aloizo03** [comment] 2023-10-31 14:55
Hello, 

I did it and i am getting the same error again.

**Comment by BloodAxe** [comment] 2023-11-09 11:30
`pip freeze` is not meant to fix the problem. This command prints versions of all installed packages that help up understand what psutil version you have and from there figure out the fix

**Comment by Louis-Dupont** [comment] 2023-12-25 22:02
@aloizo03 I will assume it's a duplicate of https://github.com/Deci-AI/super-gradients/issues/1247
If you have can run `pip freeze` feel free to post it here, and we will see if it's really a duplicate or not.

**Closed by Louis-Dupont** 2023-12-25 22:02 UTC
Labels: :bug:  Bug, :sheep: Duplicate
