### ISSUE TITLE
Getting negative coordinates for bbox

### ISSUE THREAD

**Issue by ayan-s** [Deci-AI/super-gradients#1137] opened 2023-06-06 07:23 UTC
### 🐛 Describe the bug

# positive is image
predictions = net.predict(positive, conf=0.01)
print("8 updating the conf interval")
prediction_objects = list(predictions._images_prediction_lst)[0]
bboxes = prediction_objects.prediction.bboxes_xyxy
area = []
box_final = []
width, height = positive.size
area_of_image = height*width
min_area = area_of_image*0.1
for i in range(len(bboxes)):
    if((bboxes[i][3]-bboxes[i][1])*(bboxes[i][2]-bboxes[i][0])>min_area):
        area.append((bboxes[i][3]-bboxes[i][1])*(bboxes[i][2]-bboxes[i][0]))
        box_final.append([bboxes[i][0],bboxes[i][1],bboxes[i][2],bboxes[i][3]])
box_final[42]

output:
[-1260.6094, 124.5002, 77.370636, 1841.7778]

### Versions

torch==1.13.1
torch_geometric
torchvision==0.14.1
transformers==4.20.1
Databricks version: 12.1 ML (includes Apache Spark 3.3.1, Scala 2.12)

**Comment by BloodAxe** [comment] 2023-08-10 11:59
Duplicate of https://github.com/Deci-AI/super-gradients/issues/1069

Let's assume you have a box with x1, y1, x2, y2 coordinates and your image has width W and Height H
Then what you want to do is:
```
x1 = np.clip(x1, 0, W)
x2 = np.clip(x2, 0, W)
y1 = np.clip(y1, 0, H)
y2 = np.clip(y2, 0, H)
```

**Closed by BloodAxe** 2023-08-10 11:59 UTC
