### ISSUE TITLE
How do you use DiceCEEdgeLoss for semantic segmentation multiclass?

### ISSUE THREAD

**Issue by james-imi** [Deci-AI/super-gradients#1655] opened 2023-11-22 08:24 UTC
### 🐛 Describe the bug

I have these

```
model output = torch.Size([4, 11, 640, 768])
gt_mask = torch.Size([4, 640, 768])
```

And it throws this error:
```
  File "/home/james/workspace/Adra/super-gradients/src/super_gradients/training/losses/mask_loss.py", line 38, in forward
    criterion_loss = self.criterion(predict, target)
  File "/home/james/anaconda3/envs/deci/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/james/anaconda3/envs/deci/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 1164, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/james/anaconda3/envs/deci/lib/python3.9/site-packages/torch/nn/functional.py", line 3014, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
ValueError: Expected input batch_size (11) to match target batch_size (4).
```

### Versions

Latest

**Comment by shaydeci** [comment] 2023-11-26 09:01
@james-imi Please share your code + env information.
Nevertheless, from the DiceCEEdgeLoss docs:
```
        :param preds: Model output predictions, must be in the followed format:
         [Main-feats, Aux-feats[0], ..., Aux-feats[num_auxs-1], Detail-feats[0], ..., Detail-feats[num_details-1]
```
So the model should output a list of predictions from the auxilary heads.

**Comment by Louis-Dupont** [comment] 2023-12-25 21:47
As @shaydeci explained, It looks like your model output is not compatible with `DiceCEEdgeLoss`.
`DiceCEEdgeLoss` is applied on predictions of models that have auxiliary heads. So if you are using your own model, you need to make sure to follow the format shown by @shaydeci 
If you are using a SG model and get this error, this might be a bug and we would appreciate any code to help us reproduce it.

Since there is no update for now, I'm closing this issue but feel free to re-open it if you have fresh information.

**Closed by Louis-Dupont** 2023-12-25 21:47 UTC
Labels: :grey_question:  Need more info

**Comment by james-imi** [comment] 2024-06-10 05:53
@Louis-Dupont
