### ISSUE TITLE
Is there a way to train on custom data?

### ISSUE THREAD

**Issue by byunsunghun** [Deci-AI/super-gradients#963] opened 2023-05-10 01:54 UTC
hi, I admire your skills!

Is there an easier way to train custom data?
Or does it already exist?

Thx 👍

**Comment by NatanBagrov** [comment] 2023-05-10 05:54
Hello, @byunsunghun, I hope you find the repository useful!
This is somewhat duplicate of https://github.com/Deci-AI/super-gradients/issues/929. Please go over the issue.
Also, you have a great snippet with a usage of custom dataset ("US Coins") in our [YOLO-NAS starter notebook](https://colab.research.google.com/drive/1q0RmeVRzLwRXW-h9dPFSOchwJkThUy6d)!

Good luck!

**Closed by NatanBagrov** 2023-05-10 05:54 UTC
