### ISSUE TITLE
How to extract the annotated predicted frame (image/video frame/webcam feed) and its prediction results (Objects, bboxes, confidence scores) for further processing 

### ISSUE THREAD

**Issue by maninka123** [Deci-AI/super-gradients#926] opened 2023-05-05 10:45 UTC

**Comment by BloodAxe** [comment] 2023-05-05 10:53
Duplicate of https://github.com/Deci-AI/super-gradients/issues/907

**Closed by BloodAxe** 2023-05-05 10:53 UTC
