### ISSUE TITLE
Issue with NMS not working as expected

### ISSUE THREAD

**Issue by ido-greenfeld** [Deci-AI/super-gradients#1500] opened 2023-10-05 06:46 UTC
### 🐛 Describe the bug

Hi!

I have a model which I trained using my own custom data.
I'm trying to use different values of nms_iou to clear out some duplicated detection but it doesn't seem to work as expected
I tried plugging in the IoU in  two different places, both ending in the same result - 
- `model.predict(image_paths, conf=confidence, iou=iou, batch_size=batch_size)`
- `model.set_dataset_processing_params(image_processor=image_processor, class_names=classes, iou=iou)`

Even when setting an IoU as low as 0.1, I'm still getting overlapping predictions like this - 
![image](https://github.com/Deci-AI/super-gradients/assets/53991912/4368cd30-d16c-46b9-8569-b09d332af55d)

I ended up implementing my own NMS and running it after I get the predictions, in which case it does filter as expected.
I do want to mention that my prediction are of really small objects - down to 10X10 pixels (which is crazy how well YOLO-NAS handles them!) so maybe there's a hardcoded limitation here?

Am I missing anything in my assumptions?
If you can point me to where in the code the NMS process happens that would be really helpful

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-1042-gcp-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 470.82.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:            0
CPU MHz:             2299.998
BogoMIPS:            4599.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            46080K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] onnx==1.13.0
[pip3] onnx-simplifier==0.4.33
[pip3] onnxruntime==1.13.1
[pip3] torch==1.11.0
[pip3] torchelastic==0.2.2
[pip3] torchmetrics==0.8.0
[pip3] torchtext==0.12.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchmetrics              0.8.0                    pypi_0    pypi
[conda] torchtext                 0.12.0                     py38    pytorch
[conda] torchvision               0.12.0               py38_cu113    pytorch

```

**Comment by ido-greenfeld** [comment] 2023-10-05 06:53
I found out the place I'm guessing NMS should be calculated  in - `super_gradients/training/utils/detection_utils.py`
Tried stopping there in debug but it doesn't seem as if my predict call runs through that function.
I do however see different results when changing the value of the nms_iou, so it does do something, not sure where

**Comment by BloodAxe** [comment] 2023-10-05 08:36
Thanks for reporting this. Can you please specify SG version did you use and what model architecture you were training? If that's not too much to ask - can you also attach the trained weights so that we can reproduce the issue on our end?

**Comment by ido-greenfeld** [comment] 2023-10-05 13:19
I'm using SG==3.2.0
Architecture is yolo_nas_s

Unfortunately I can't provide the weights or the images used for inference

**Comment by ikranergiz** [comment] 2023-11-06 19:47
I'm also getting overlapping predictions like this. Here's [my Colab notebook link](https://colab.research.google.com/drive/1lh1SsptEza78Ob6Bzj65y5NPNeDkRzWl?usp=sharing). 

When I ran the predict function without passing the 'conf' parameter, it didn't show any bounding boxes. However, when I passed it in, multiple bounding boxes were displayed. 

![download (2)](https://github.com/Deci-AI/super-gradients/assets/56405604/d4ce081c-3767-4413-ac1a-79e39c91f8b7)

I also attach my best weight files. Here's the [link](https://drive.google.com/file/d/1-NVUyJcdZkgJDdLDv_hGr4uS0anQqX6U/view?usp=sharing)

> Thanks for reporting this. Can you please specify SG version did you use and what model architecture you were training? If that's not too much to ask - can you also attach the trained weights so that we can reproduce the issue on our end?

**Comment by BloodAxe** [comment] 2023-12-22 10:04
Can you please try with latest SG 3.5 release? I feel there was a number of bugfixes/improvements over predict() and simply updating to recent SG version may fix the issue.

**Comment by BloodAxe** [comment] 2024-02-12 14:07
Closing PR is could not reproduce. Feel free to re-open if you encounter this error on 3.6 release.

**Closed by BloodAxe** 2024-02-12 14:07 UTC
Labels: :bug:  Bug
