### ISSUE TITLE
getting error installing super_gradients

### ISSUE THREAD

**Issue by andysingal** [Deci-AI/super-gradients#1653] opened 2023-11-21 13:41 UTC
### 🐛 Describe the bug

tried installing
and got error:
```
Requirement already satisfied: PyYAML>=5.1.0 in /opt/homebrew/lib/python3.11/site-packages (from omegaconf->super-gradients) (6.0.1)
INFO: pip is looking at multiple versions of onnx to determine which version is compatible with other requirements. This could take a while.
Collecting onnx>=1.10.1 (from super-gradients)
  Using cached onnx-1.14.1-cp311-cp311-macosx_10_12_universal2.whl.metadata (15 kB)
  Using cached onnx-1.14.0-cp311-cp311-macosx_10_12_universal2.whl (15.2 MB)
  Using cached onnx-1.13.1-cp311-cp311-macosx_10_12_universal2.whl (14.1 MB)
  Using cached onnx-1.13.0-cp311-cp311-macosx_10_12_universal2.whl (14.0 MB)
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/pb/j6hg1j197710n00qy9df10dw0000gn/T/pip-install-_d0ef3v_/onnx_edafabf106254ec1b7c501481ce7f4c2/setup.py", line 81, in <module>
          assert CMAKE, "Could not find cmake executable!"
      AssertionError: Could not find cmake executable!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

### Versions

```
Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.18 | packaged by conda-forge | (default, Oct 10 2023, 15:46:56)  [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-13.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.13.1
[pip3] torchvision==0.13.1a0
[conda] numpy                     1.19.5           py38he594345_3    conda-forge
[conda] pytorch                   1.13.1                  py3.8_0    pytorch
[conda] torchvision               0.13.1          cpu_py38he5d19f7_0  
```

**Comment by BloodAxe** [comment] 2023-11-21 14:20
As the error suggests, you need to have build tools (xcode command line tools and cmake) to compile dependent packages, because precompiled version of the packages is not available for your platform in pip.
We have a fixed onnx version which is pretty old, which may be a root cause of this. We will check whether we can lift up the version requirements of onnx.

**Comment by andysingal** [comment] 2023-11-22 16:06
Problem still persists:
```
pip install -r requirements.txt 
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
Collecting super_gradients==3.1.3 (from -r requirements.txt (line 1))
  Using cached super_gradients-3.1.3-py3-none-any.whl.metadata (35 kB)
Collecting segment_anything (from -r requirements.txt (line 2))
  Downloading segment_anything-1.0-py3-none-any.whl (36 kB)
Collecting supervision (from -r requirements.txt (line 3))
  Downloading supervision-0.16.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: opencv-python in /opt/homebrew/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (4.8.1.78)
Requirement already satisfied: torch>=1.9.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: tqdm>=4.57.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (4.66.1)
Collecting boto3>=1.17.15 (from super_gradients==3.1.3->-r requirements.txt (line 1))
  Using cached boto3-1.29.5-py3-none-any.whl.metadata (6.7 kB)
Collecting jsonschema>=3.2.0 (from super_gradients==3.1.3->-r requirements.txt (line 1))
  Using cached jsonschema-4.20.0-py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: Deprecated>=1.2.11 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (1.2.14)
Requirement already satisfied: scipy>=1.6.1 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (1.11.3)
Requirement already satisfied: matplotlib>=3.3.4 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (3.8.1)
Requirement already satisfied: psutil>=5.8.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (5.9.6)
Requirement already satisfied: tensorboard>=2.4.1 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (2.15.1)
Requirement already satisfied: setuptools>=21.0.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (68.2.2)
Collecting coverage~=5.3.1 (from super_gradients==3.1.3->-r requirements.txt (line 1))
  Using cached coverage-5.3.1.tar.gz (684 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torchvision>=0.10.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (0.16.0)
Collecting sphinx~=4.0.2 (from super_gradients==3.1.3->-r requirements.txt (line 1))
  Using cached Sphinx-4.0.3-py3-none-any.whl (2.9 MB)
Collecting sphinx-rtd-theme (from super_gradients==3.1.3->-r requirements.txt (line 1))
  Using cached sphinx_rtd_theme-1.3.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting torchmetrics==0.8 (from super_gradients==3.1.3->-r requirements.txt (line 1))
  Using cached torchmetrics-0.8.0-py3-none-any.whl (408 kB)
Requirement already satisfied: hydra-core>=1.2.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: omegaconf in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3->-r requirements.txt (line 1)) (2.3.0)
INFO: pip is looking at multiple versions of super-gradients to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.13.1 (from super-gradients) (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.13.1
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
```

**Comment by andysingal** [comment] 2023-11-24 16:06
@BloodAxe I installed Xcode
```
1007  xcode-select --install
 1008  brew install mas
 1009  mas search xcode
 1010  as install 497799835
 1011  mas install 497799835
 1012  pip install super_gradients==3.1.3
```
but still getting error:
```
Requirement already satisfied: hydra-core>=1.2.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3) (1.2.0)
Requirement already satisfied: omegaconf in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.1.3) (2.3.0)
INFO: pip is looking at multiple versions of super-gradients to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.13.1 (from super-gradients) (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.13.1
```

**Comment by BloodAxe** [comment] 2023-11-24 16:21
It seems you are using old version of SG (3.1.3) and trying to install it for python 3.11. 
That version has support of 3.10 and not 3.11, which may explain why you can't install.
I suggest you give it a try to 3.5.0 release of SG that we rolled out recently

**Comment by andysingal** [comment] 2023-11-24 16:24
> It seems you are using old version of SG (3.1.3) and trying to install it for python 3.11. That version has support of 3.10 and not 3.11, which may explain why you can't install. I suggest you give it a try to 3.5.0 release of SG that we rolled out recently

same error:
```
pip install super_gradients==3.5.0
Collecting super_gradients==3.5.0
  Downloading super_gradients-3.5.0-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: torch>=1.9.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (2.1.0)
Requirement already satisfied: tqdm>=4.57.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (4.66.1)
Collecting boto3>=1.17.15 (from super_gradients==3.5.0)
  Using cached boto3-1.29.6-py3-none-any.whl.metadata (6.7 kB)
Collecting jsonschema>=3.2.0 (from super_gradients==3.5.0)
  Using cached jsonschema-4.20.0-py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: Deprecated>=1.2.11 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (1.2.14)
Requirement already satisfied: opencv-python>=4.5.1 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (4.8.1.78)
Requirement already satisfied: scipy>=1.6.1 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (1.11.3)
Requirement already satisfied: matplotlib>=3.3.4 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (3.8.1)
Requirement already satisfied: psutil>=5.8.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (5.9.6)
Requirement already satisfied: tensorboard>=2.4.1 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (2.15.1)
Requirement already satisfied: setuptools>=21.0.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (68.2.2)
Collecting coverage~=5.3.1 (from super_gradients==3.5.0)
  Using cached coverage-5.3.1.tar.gz (684 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torchvision>=0.10.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (0.16.0)
Collecting sphinx~=4.0.2 (from super_gradients==3.5.0)
  Using cached Sphinx-4.0.3-py3-none-any.whl (2.9 MB)
Collecting sphinx-rtd-theme (from super_gradients==3.5.0)
  Using cached sphinx_rtd_theme-1.3.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting torchmetrics==0.8 (from super_gradients==3.5.0)
  Using cached torchmetrics-0.8.0-py3-none-any.whl (408 kB)
Requirement already satisfied: hydra-core>=1.2.0 in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (1.2.0)
Requirement already satisfied: omegaconf in /opt/homebrew/lib/python3.11/site-packages (from super_gradients==3.5.0) (2.3.0)
INFO: pip is looking at multiple versions of super-gradients to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.13.1 (from super-gradients) (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.13.1
```

**Comment by ZYX-MLer** [comment] 2023-11-27 08:05
I meet the same problem on apple m2 pro

**Comment by yonglee7015** [comment] 2023-12-24 13:24
> I change the python from 3.11 to 3.10, the installation is successful

this the correct answer, python 3.10 is key reason

**Closed** 2023-12-25 20:59 UTC

**Comment by abhishek-dudeja** [comment] 2025-05-04 10:36
@BloodAxe - any plans to provide SG support on newer python versions?
