### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by frankvp11** [Deci-AI/super-gradients#946] opened 2023-05-07 14:39 UTC
I am trying to train YOLONAS on a 100k dataset of mathematical images. However, upon running the necessary train commands, it errors out giving me the following error:
```
OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 14.75 GiB total capacity; 13.38 GiB already allocated; 2.81 MiB free; 13.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
I already halved the batch_size (as suggested by https://stackoverflow.com/questions/59129812/how-to-avoid-cuda-out-of-memory-in-pytorch) however still the same problem. 

### To Reproduce
To reproduce this, I just copied over the training colab file called Intro to SuperGradients + YOLONAS Starter Notebook.ipynb into my data-prep file. 

### Expected behavior
I expected it to start training
### Environment:
Google Colab (with GPU)
super-gradients==3.1.0

**Comment by frankvp11** [comment] 2023-05-07 14:41
My *guess* is that it comes because the coco_detection_yolo_format_train method caches everything which fills up the memory (no idea how to fix)

**Comment by shaydeci** [comment] 2023-05-07 14:47
@frankvp11 Hello (:
Actually, caching is just for the labels, and they are all stored in RAM so CUDA memory shouldn't be affected.

It seems that even though you halved the batch size, it might is still be too large (colab does not have so much GPU memory...).

Can you detail whther this happens toyou during validation or training part?
If it happens in validation, it could be that you also need to modify the validation batch size.

**Comment by frankvp11** [comment] 2023-05-07 14:49
I modifying all the batch sizes to be 2 now (used to be 16) and it's now "stuck" as in hasn't changed in 5 minutes from this:
```
[2023-05-07 14:44:23] INFO - sg_trainer.py - Using EMA with params {'decay': 0.9, 'decay_type': 'threshold'}
The console stream is now moved to checkpoints/my_first_yolonas_run/console_May07_14_44_23.txt
[2023-05-07 14:44:26] INFO - sg_trainer_utils.py - TRAINING PARAMETERS:
    - Mode:                         Single GPU
    - Number of GPUs:               1          (1 available on the machine)
    - Dataset size:                 85000      (len(train_set))
    - Batch size per GPU:           2          (batch_size)
    - Batch Accumulate:             1          (batch_accumulate)
    - Total batch size:             2          (num_gpus * batch_size)
    - Effective Batch size:         2          (num_gpus * batch_size * batch_accumulate)
    - Iterations per epoch:         42500      (len(train_loader))
    - Gradient updates per epoch:   42500      (len(train_loader) / batch_accumulate)
```
So it could be that the batch size might still have been to large, however not much is happening right now

**Comment by BloodAxe** [comment] 2023-05-07 15:15
First, YOLO-NAS should train just fine with bs=2 on Colab. You can easily verify this by taking starter notebook, and replacing `yolo_nas_s` to `yolo_nas_l`. This should train fine with smaller batch size.

Second, since your notebook contains additional imports & training commands using ultralitics - `!yolo task=detect mode=train model=yolov8x.yaml data=/content/dataset/data.yaml epochs=5 device=0` it could be still using GPU. 

Try removing all unnecessary cells from your notebook that you don't strictly require (E.g any imports of ultralitics,  inference calls `!yolo task=detect mode=train`).

After you cleaned up the notebook please restart it to ensure you don't have any leftovers in memory and restart the training of YOLO-NAS.

**Comment by frankvp11** [comment] 2023-05-07 15:32
Yes. As I specified in the previous message, you should have read the text boxes. I specifically put text boxes saying which part was for yolo (my initial model) and for yolonas (lower down). If you hadn't run the code between the two text boxes, your previous message wouldn't be applicable. Those imports wouldn't be affecting anything if you hadn't run those.

**Comment by frankvp11** [comment] 2023-05-09 21:51
Any update on this?

**Comment by Louis-Dupont** [comment] 2023-05-11 11:52
Hi @frankvp11 ,
I am really not sure why you would have a problem  `batch_size` of 2 on `yolo_nas_s `.
You can try out a few different configurations and see what works/what doesn't. This can help us better understand the root of the problem you are facing.
- Run on another dataset (ideally small images) to see if it runs faster
- Apply `model.predict` on some of your images (see [doc](https://docs.deci.ai/super-gradients/documentation/source/ModelPredictions.html))
- Run the training again and monitor the resources 
- Test the model (see snippet) and see if it is also slow

```python
trainer.test(
    model=model,
    test_loader=val_data,
    test_metrics_list=[
        DetectionMetrics_050(
            score_thres=0.1,
            top_k_predictions=300,
            # NOTE: num_classes needs to be defined here
            num_cls=len(dataset_params["classes"]),
            normalize_targets=True,
            post_prediction_callback=PPYoloEPostPredictionCallback(score_threshold=0.01, nms_top_k=1000, max_predictions=300, nms_threshold=0.7),
        )
    ],
)
```

**Comment by BloodAxe** [comment] 2023-05-12 08:35
Closing as can't reproduce. Your notebook that you've shared seems to be using Kaggle datasets and require external kaggle.json with access credentials. 
You can share the Kaggle notebook that do not require any additional steps to even run the notebook and re-open the issue.

**Closed by BloodAxe** 2023-05-12 08:35 UTC
Labels: help wanted, :grey_question: Question
