### ISSUE TITLE
CUDA error prventing me from training YOLONAS

### ISSUE THREAD

**Issue by ahmed1alqulayti** [Deci-AI/super-gradients#1004] opened 2023-05-15 06:02 UTC
Hi all, I used this [code](https://www.kaggle.com/code/harpdeci/yolo-nas-hard-hat-and-vest) to train the yolonas model on my dataset, I checked the classes and they are zero-based, and I used conda environment with 3.9 python version.

![Screenshot from 2023-05-15 08-58-55](https://github.com/Deci-AI/super-gradients/assets/92484568/34755685-1b7f-4d38-837a-21844ec57457)

**Comment by BloodAxe** [comment] 2023-05-15 06:46
This error usually indicates there is an error with number of classes you define when instantiating a model and actual class indexes. For intances, you set `num_classes=10` but the labels present in the dataset are not zero-based: `1,2,3,4,5,6,7,8,9,10`. We require class labels to stay in range [0, num_classes), like for regular CE loss.
Please double-check that labels in your dataset are zero-based.

**Comment by BloodAxe** [comment] 2023-05-15 06:49
Possible duplicate of https://github.com/Deci-AI/super-gradients/issues/995

**Comment by ahmed1alqulayti** [comment] 2023-05-15 07:17
@BloodAxe  Hello dear, thank you for your help.
Yes, I made sure it's zero-based as you can see in the figure below:
![Screenshot from 2023-05-15 10-14-18](https://github.com/Deci-AI/super-gradients/assets/92484568/b189764e-69d6-4fdc-a025-a7a0d2252b44)

**Comment by ahmed1alqulayti** [comment] 2023-05-15 07:20
Also, I set the number of classes correctly to 12, as you can see in the figure:
![Screenshot from 2023-05-15 10-18-29](https://github.com/Deci-AI/super-gradients/assets/92484568/7cb4a3b5-948b-4f0f-afa8-5096ff834697)

**Comment by ahmed1alqulayti** [comment] 2023-05-15 08:30
@Louis-Dupont Hello dear,

I got this error
![Screenshot from 2023-05-15 11-29-58](https://github.com/Deci-AI/super-gradients/assets/92484568/df693a99-7309-4677-8a49-b27ef7a38c0a)

**Comment by ahmed1alqulayti** [comment] 2023-05-15 08:33
Btw I run another code to make sure my label index of any object on the range of 0 to 11, it was fine, so I don't know what is the issue:
![Screenshot from 2023-05-15 11-32-32](https://github.com/Deci-AI/super-gradients/assets/92484568/967890e3-ad93-4180-9431-6bd287bf0466)

**Comment by Louis-Dupont** [comment] 2023-05-15 09:00
Can you check directly the output of the dataloader ?
``` python
_images, labels = next(iter(train_dataloader))
print(labels[:, 1]) # will show only the classes
```
Ideally iterate over the whole dataset and check all unique values

**Comment by ahmed1alqulayti** [comment] 2023-05-15 10:21
@Louis-Dupont This was the results:
![Screenshot from 2023-05-15 13-20-45](https://github.com/Deci-AI/super-gradients/assets/92484568/4f5c9b7b-6592-46e0-93aa-195144adff97)

**Comment by Louis-Dupont** [comment] 2023-05-15 10:48
What about the full dataset? I think there might be a -1 label somewhere
``` python
unique_cls_id = {int(cls_id) for _, label in train_dataloader for cls_id in label[:, 1]}
print(unique_cls_id)
```

**Comment by ahmed1alqulayti** [comment] 2023-05-15 10:57
@Louis-Dupont You absolutely right, I don't know why my code did not catch that, but anyway, I will try to find it and change it, and update you with the result.

**Comment by ahmed1alqulayti** [comment] 2023-05-16 05:55
I finished training the model and It's working fine, thank you all for your help. @Louis-Dupont @BloodAxe

**Comment by Louis-Dupont** [comment] 2023-05-16 06:55
Great! Closing this issue.

**Closed by Louis-Dupont** 2023-05-16 06:55 UTC
Labels: duplicate, YoloNAS
